# Numpy
NumPy (Numerical Python) is the fundamental open-source library for
scientific computing in Python, providing support for large, multi-dimensional
arrays and matrices.

## Key Features of NumPy

Ndarray Object: The core is the ndarray, a fast, flexible, homogeneous ,dimensional array object that enables efficient storage and manipulation of numerical data.

Performance: Written partially in C or C++, NumPy operations are significantly faster than standard Python lists, making it ideal for heavy computation.

Mathematical Functions: Includes tools for linear algebra, Fourier transforms, random number generation, and  ophisticated sorting/selection.

Fixed-Size Arrays: Unlike Python lists, NumPy arrays have a fixed size at creation, optimizing memory usage and processing speed.

In [1]:
import numpy as np

In [ ]:
# create a list of sales and convert it to a numpy array

sales = [450,123,1200,765,1230]

arr  = np.array(sales)

print(sales,type(sales))

print(arr,type(arr))

In [ ]:
np.array([3,4,5,"hello"])

In [ ]:
np.array([3,4,5,9.87,"t"])

How fast are arrays?

In [ ]:
# %%timeit
# total = 0
# for i in range(10000000):
#     total += i

In [ ]:
# %%timeit
# arr = np.arange(10000000)
# np.sum(arr)

# NDarray

In [ ]:
# 1D array

arr1d = np.array( [3,6,7,4] )
print(arr1d)

In [ ]:
arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)

In [ ]:
arr3d = np.array( [ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ] )
print(arr3d)

# calculation in array

In [ ]:
amount = [142, 245, 350, 440, 590]

for i in amount:
    print(i + 100)

In [ ]:
arr = np.array([142, 245, 350, 440, 590])
print(arr + 100)
print(arr * 2)
print(arr / 2)

## attributes in numpy

In [ ]:
arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(type(arr))
print(arr.dtype)


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
# shape of the array

arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(arr.shape)

arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)
print(arr2d.shape)

print(arr3d)
print(arr3d.shape)

In [ ]:
# Size of the array

print( arr2d)
print("shape - ", arr2d.shape)
print("size - ", arr2d.size)


In [ ]:
# ndim
print("number of dimensions - ", arr2d.ndim)
print("number of dimensions - ", arr3d.ndim)


## Change data type of an array

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

arr = arr.astype(float)
print(arr)

arr = arr.astype(str)
print(arr)


In [ ]:
arr = np.array([1.453, 2.345, 3.567,8.7665,12.765])
print(arr)

arr = arr.astype(int)
print(arr)

## create different type of arrays

In [ ]:
# Arange

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(20,5,-1))
print(np.arange(1,10,0.845))


In [ ]:
# Zeros

print(np.zeros(5))
print(np.zeros((3,4)))

In [ ]:
# np.ones

print(np.ones(5))
print(np.ones((3,4)))

In [ ]:
# np.full

print(np.full(5, 9))
print(np.full((3,4), 5))

In [ ]:
# Linspace
print(np.linspace(5, 17, 50))

In [ ]:
# random numbers
np.random.randint(1,100,10)

In [ ]:
# random numbers
np.random.randint(1,100,size=(5,4))

## Aggregation in numpy

In [ ]:
# sum, min, max, average, count, std, var
sales = np.array([450,1200,780,435,136])

In [ ]:
sales

In [ ]:
sales.sum()

In [ ]:
sales.min()

In [ ]:
sales.mean()   #avearage of array

In [ ]:
sales.std()

In [ ]:
sales.var()

In [ ]:
sales.size   # count the elements

## Indexing And Slicing

In [ ]:
sales

In [ ]:
sales[1]

In [ ]:
sales[-1]

In [ ]:
sales[2] = 300

In [ ]:
sales

In [ ]:
sales[1:4]

## Indexing And Slicing in 2D

In [ ]:
np.random.seed(5)
arr = np.random.randint(1,100,size=(5,4))
print(arr)

In [ ]:
arr[2]

In [ ]:
arr[2,2]

In [ ]:
print(arr)
arr[0:2,2]

In [ ]:
arr[0:5,2]

In [ ]:
arr[ : :2,::2]

## Array filtering

In [61]:
sales = np.array([450,  99, 300, 435, 136])
sales

array([450,  99, 300, 435, 136])

In [59]:
sales > 400

array([ True, False, False,  True, False])

In [ ]:
sales

In [60]:
sales[sales>400]

array([450, 435])

In [ ]:
# Creating an array of age with random numbers from 12 to 50
age = np.random.randint(12,50,10)
print(age)

[12 28 16 48 39 43 14 16 31 31]


In [ ]:
# find all age above or equal to 18


In [ ]:
# find all the even age?

## Views In Numy

In [ ]:
arr = np.array([7,9,0,2,4,6,12,5])
print(arr)

arr_view = arr[0:4]
print(arr_view)

arr_view[1] = 55

print(arr)
print(arr_view)

[ 7  9  0  2  4  6 12  5]
[7 9 0 2]
[ 7 55  0  2  4  6 12  5]
[ 7 55  0  2]


## Broadcasting In Numpy

In [76]:
sales = np.array([450,1200,780,435,136])
print(sales)
print(sales*2)
print(sales/5)

[ 450 1200  780  435  136]
[ 900 2400 1560  870  272]
[ 90.  240.  156.   87.   27.2]


In [82]:
a = np.array([4,5,6,7])
b = np.array([[9,1,6,6],[21,67,7,7]])

print(a)
print()
print(b)
print()

print(a+b)

[4 5 6 7]

[[ 9  1  6  6]
 [21 67  7  7]]

[[13  6 12 13]
 [25 72 13 14]]


## np.where

In [2]:
sales = np.array([450,1200,780,435,136])

np.where(sales>500,"high","Low")

array(['Low', 'high', 'high', 'Low', 'Low'], dtype='<U4')

In [3]:
np.where(sales>500,sales*2,sales/2)

array([ 225. , 2400. , 1560. ,  217.5,   68. ])

In [ ]:
# Find which numbers are even or odd from 1 to 10 ?
