In [1]:
import numpy as np

In [7]:
sales = [450,123,1200,765,1230]

arr  = np.array(sales)

print(sales)
print(arr)

[450, 123, 1200, 765, 1230]
[ 450  123 1200  765 1230]


In [4]:
type(arr)

numpy.ndarray

In [7]:
%%timeit
total = 0
for i in range(10000000):
    total += i

1.26 s ± 121 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%timeit
arr = np.arange(10000000)
np.sum(arr)

45.1 ms ± 770 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
arr1d = np.array( [3,6,7,4] )
print(arr1d)

[3 6 7 4]


In [3]:
arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)

[[5 4 3 2]
 [9 0 2 5]
 [1 1 5 4]]


In [5]:
arr1d + 100

array([103, 106, 107, 104])

In [8]:
sales

[450, 123, 1200, 765, 1230]

In [10]:
arr *15/100

array([ 67.5 ,  18.45, 180.  , 114.75, 184.5 ])

In [16]:
np.arange(1,11,2.5)

array([1. , 3.5, 6. , 8.5])

In [17]:
arr

array([ 450,  123, 1200,  765, 1230])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.dtype

dtype('int64')

In [20]:
name = np.array(['rohan',"mohit","sumit"])
name

array(['rohan', 'mohit', 'sumit'], dtype='<U5')

In [22]:
name.dtype

dtype('<U5')

In [24]:
name.size

3

In [28]:
arr2d.shape

(3, 4)

In [29]:
arr2d.ndim

2

In [31]:
name.ndim

1

In [37]:
arr.astype(float)

array([ 450.,  123., 1200.,  765., 1230.])

In [38]:
arr

array([ 450,  123, 1200,  765, 1230])

In [42]:
arr2d.astype(float)

array([[5., 4., 3., 2.],
       [9., 0., 2., 5.],
       [1., 1., 5., 4.]])

In [48]:
arr2d.reshape((2,6))

array([[5, 4, 3, 2, 9, 0],
       [2, 5, 1, 1, 5, 4]])

In [49]:
a = np.arange(50)

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
a.reshape((2,5,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [53]:
# (sheet,row,col)

In [2]:
# sum, min, max...
sales = np.array([450,1200,780,435,136])

In [56]:
sales

array([ 450, 1200,  780,  435,  136])

In [57]:
sales.sum()

np.int64(3001)

In [58]:
sales.min()

np.int64(136)

In [60]:
sales.mean()   #avg

np.float64(600.2)

In [62]:
sales.std()

np.float64(362.60744614527704)

In [64]:
sales.size

5

In [65]:
sales

array([ 450, 1200,  780,  435,  136])

In [67]:
sales[2] = 300

In [68]:
sales

array([ 450, 1200,  300,  435,  136])

In [69]:
sales[1:4]

array([1200,  300,  435])

In [71]:
sales > 400

array([ True,  True, False,  True, False])

In [72]:
sales

array([ 450, 1200,  300,  435,  136])

In [73]:
sales[sales>400]

array([ 450, 1200,  435])

In [5]:
sales[sales %2 == 0]

array([ 450, 1200,  780,  136])

In [6]:
sales

array([ 450, 1200,  780,  435,  136])

In [8]:
b = sales[1:4]

In [10]:
b[0] = 99

In [11]:
b

array([ 99, 780, 435])

In [12]:
sales

array([450,  99, 780, 435, 136])

In [23]:
a = np.array([4,5,6,7])
b = np.array([[9,1,6,6],[21,67,7,7]])

b + 50

array([[ 59,  51,  56,  56],
       [ 71, 117,  57,  57]])

In [24]:
sales

array([450,  99, 780, 435, 136])

In [25]:
np.where(sales>400,"high","Low")

array(['high', 'Low', 'high', 'high', 'Low'], dtype='<U4')