# Numpy
NumPy (Numerical Python) is the fundamental open-source library for
scientific computing in Python, providing support for large, multi-dimensional
arrays and matrices.

## Key Features of NumPy

Ndarray Object: The core is the ndarray, a fast, flexible, homogeneous ,dimensional array object that enables efficient storage and manipulation of numerical data.

Performance: Written partially in C or C++, NumPy operations are significantly faster than standard Python lists, making it ideal for heavy computation.

Mathematical Functions: Includes tools for linear algebra, Fourier transforms, random number generation, and  ophisticated sorting/selection.

Fixed-Size Arrays: Unlike Python lists, NumPy arrays have a fixed size at creation, optimizing memory usage and processing speed.

In [1]:
import numpy as np

In [2]:
# create a list of sales and convert it to a numpy array

sales = [450,123,1200,765,1230]

arr  = np.array(sales)

print(sales,type(sales))

print(arr,type(arr))

[450, 123, 1200, 765, 1230] <class 'list'>
[ 450  123 1200  765 1230] <class 'numpy.ndarray'>


In [3]:
np.array([3,4,5,"hello"])

array(['3', '4', '5', 'hello'], dtype='<U21')

In [4]:
np.array([3,4,5,9.87,"t"])

array(['3', '4', '5', '9.87', 't'], dtype='<U32')

How fast are arrays?

In [10]:
# %%timeit
# total = 0
# for i in range(10000000):
#     total += i

In [11]:
# %%timeit
# arr = np.arange(10000000)
# np.sum(arr)

# NDarray

In [12]:
# 1D array

arr1d = np.array( [3,6,7,4] )
print(arr1d)

[3 6 7 4]


In [13]:
arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)

[[5 4 3 2]
 [9 0 2 5]
 [1 1 5 4]]


In [14]:
arr3d = np.array( [ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ] )
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# calculation in array

In [15]:
amount = [142, 245, 350, 440, 590]

for i in amount:
    print(i + 100)

242
345
450
540
690


In [16]:
arr = np.array([142, 245, 350, 440, 590])
print(arr + 100)
print(arr * 2)
print(arr / 2)

[242 345 450 540 690]
[ 284  490  700  880 1180]
[ 71.  122.5 175.  220.  295. ]


## attributes in numpy

In [17]:
arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(type(arr))
print(arr.dtype)


[142 245 350 440 590]
<class 'numpy.ndarray'>
int64


In [18]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(type(arr))
print(arr.dtype)

['apple' 'banana' 'cherry']
<class 'numpy.ndarray'>
<U6


In [19]:
# shape of the array

arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(arr.shape)

arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)
print(arr2d.shape)

print(arr3d)
print(arr3d.shape)

[142 245 350 440 590]
(5,)
[[5 4 3 2]
 [9 0 2 5]
 [1 1 5 4]]
(3, 4)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [20]:
# Size of the array

print( arr2d)
print("shape - ", arr2d.shape)
print("size - ", arr2d.size)


[[5 4 3 2]
 [9 0 2 5]
 [1 1 5 4]]
shape -  (3, 4)
size -  12


In [21]:
# ndim
print("number of dimensions - ", arr2d.ndim)
print("number of dimensions - ", arr3d.ndim)


number of dimensions -  2
number of dimensions -  3


## Change data type of an array

In [22]:
arr = np.array([1,2,3,4])
print(arr)

arr = arr.astype(float)
print(arr)

arr = arr.astype(str)
print(arr)


[1 2 3 4]
[1. 2. 3. 4.]
['1.0' '2.0' '3.0' '4.0']


In [23]:
arr = np.array([1.453, 2.345, 3.567,8.7665,12.765])
print(arr)

arr = arr.astype(int)
print(arr)

[ 1.453   2.345   3.567   8.7665 12.765 ]
[ 1  2  3  8 12]


## create different type of arrays

In [24]:
# Arange

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(20,5,-1))
print(np.arange(1,10,0.845))


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6]
[1.    1.845 2.69  3.535 4.38  5.225 6.07  6.915 7.76  8.605 9.45 ]


In [25]:
# Zeros

print(np.zeros(5))
print(np.zeros((3,4)))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
# np.ones

print(np.ones(5))
print(np.ones((3,4)))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# np.full

print(np.full(5, 9))
print(np.full((3,4), 5))

[9 9 9 9 9]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [28]:
# Linspace
print(np.linspace(5, 17, 50))

[ 5.          5.24489796  5.48979592  5.73469388  5.97959184  6.2244898
  6.46938776  6.71428571  6.95918367  7.20408163  7.44897959  7.69387755
  7.93877551  8.18367347  8.42857143  8.67346939  8.91836735  9.16326531
  9.40816327  9.65306122  9.89795918 10.14285714 10.3877551  10.63265306
 10.87755102 11.12244898 11.36734694 11.6122449  11.85714286 12.10204082
 12.34693878 12.59183673 12.83673469 13.08163265 13.32653061 13.57142857
 13.81632653 14.06122449 14.30612245 14.55102041 14.79591837 15.04081633
 15.28571429 15.53061224 15.7755102  16.02040816 16.26530612 16.51020408
 16.75510204 17.        ]


In [30]:
# sum, min, max...
sales = np.array([450,1200,780,435,136])

In [ ]:
sales

In [ ]:
sales.sum()

In [ ]:
sales.min()

In [ ]:
sales.mean()   #avg

In [ ]:
sales.std()

In [ ]:
sales.size

In [ ]:
sales

In [ ]:
sales[2] = 300

In [ ]:
sales

In [ ]:
sales[1:4]

In [ ]:
sales > 400

In [ ]:
sales

In [ ]:
sales[sales>400]

In [ ]:
sales[sales %2 == 0]

In [ ]:
sales

In [ ]:
b = sales[1:4]

In [ ]:
b[0] = 99

In [ ]:
b

In [ ]:
sales

In [ ]:
a = np.array([4,5,6,7])
b = np.array([[9,1,6,6],[21,67,7,7]])

b + 50

In [ ]:
sales

In [ ]:
np.where(sales>400,"high","Low")