# Numpy
NumPy (Numerical Python) is the fundamental open-source library for
scientific computing in Python, providing support for large, multi-dimensional
arrays and matrices.

## Key Features of NumPy

Ndarray Object: The core is the ndarray, a fast, flexible, homogeneous ,dimensional array object that enables efficient storage and manipulation of numerical data.

Performance: Written partially in C or C++, NumPy operations are significantly faster than standard Python lists, making it ideal for heavy computation.

Mathematical Functions: Includes tools for linear algebra, Fourier transforms, random number generation, and  ophisticated sorting/selection.

Fixed-Size Arrays: Unlike Python lists, NumPy arrays have a fixed size at creation, optimizing memory usage and processing speed.

In [ ]:
import numpy as np

In [ ]:
# create a list of sales and convert it to a numpy array

sales = [450,123,1200,765,1230]

arr  = np.array(sales)

print(sales,type(sales))

print(arr,type(arr))

In [ ]:
np.array([3,4,5,"hello"])

In [ ]:
np.array([3,4,5,9.87,"t"])

How fast are arrays?

In [ ]:
# %%timeit
# total = 0
# for i in range(10000000):
#     total += i

In [ ]:
# %%timeit
# arr = np.arange(10000000)
# np.sum(arr)

# NDarray

In [ ]:
# 1D array

arr1d = np.array( [3,6,7,4] )
print(arr1d)

In [ ]:
arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)

In [ ]:
arr3d = np.array( [ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ] )
print(arr3d)

# calculation in array

In [ ]:
amount = [142, 245, 350, 440, 590]

for i in amount:
    print(i + 100)

In [ ]:
arr = np.array([142, 245, 350, 440, 590])
print(arr + 100)
print(arr * 2)
print(arr / 2)

## attributes in numpy

In [ ]:
arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(type(arr))
print(arr.dtype)


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
# shape of the array

arr = np.array([142, 245, 350, 440, 590])
print(arr)
print(arr.shape)

arr2d = np.array( [ [5,4,3,2],[9,0,2,5],[1,1,5,4] ]  )
print(arr2d)
print(arr2d.shape)

print(arr3d)
print(arr3d.shape)

In [ ]:
# Size of the array

print( arr2d)
print("shape - ", arr2d.shape)
print("size - ", arr2d.size)


In [ ]:
# ndim
print("number of dimensions - ", arr2d.ndim)
print("number of dimensions - ", arr3d.ndim)


## Change data type of an array

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

arr = arr.astype(float)
print(arr)

arr = arr.astype(str)
print(arr)


In [ ]:
arr = np.array([1.453, 2.345, 3.567,8.7665,12.765])
print(arr)

arr = arr.astype(int)
print(arr)

## create different type of arrays

In [ ]:
# Arange

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.arange(20,5,-1))
print(np.arange(1,10,0.845))


In [ ]:
# Zeros

print(np.zeros(5))
print(np.zeros((3,4)))

In [ ]:
# np.ones

print(np.ones(5))
print(np.ones((3,4)))

In [ ]:
# np.full

print(np.full(5, 9))
print(np.full((3,4), 5))

In [ ]:
# Linspace
print(np.linspace(5, 17, 50))

In [29]:
# random numbers
np.random.randint(1,100,10)

array([43, 84, 73, 57, 76, 61, 89, 94, 97, 72], dtype=int32)

In [31]:
# random numbers
np.random.randint(1,100,size=(5,4))

array([[58,  7, 89, 39],
       [ 5, 15, 89, 49],
       [80, 92, 58, 85],
       [76, 30, 72, 80],
       [ 5, 49,  4,  9]], dtype=int32)

## Aggregation in numpy

In [ ]:
# sum, min, max, average, count, std, var
sales = np.array([450,1200,780,435,136])

In [ ]:
sales

In [ ]:
sales.sum()

In [ ]:
sales.min()

In [ ]:
sales.mean()   #avearage of array

In [ ]:
sales.std()

In [ ]:
sales.var()

In [ ]:
sales.size   # count the elements

## Indexing And Slicing

In [12]:
sales

array([ 450, 1200,  780,  435,  136])

In [15]:
sales[1]

np.int64(1200)

In [19]:
sales[-1]

np.int64(136)

In [16]:
sales[2] = 300

In [17]:
sales

array([ 450, 1200,  300,  435,  136])

In [20]:
sales[1:4]

array([1200,  300,  435])

## Indexing And Slicing in 2D

In [38]:
np.random.seed(5)
arr = np.random.randint(1,100,size=(5,4))
print(arr)

[[79 62 17 74]
 [ 9 63 28 31]
 [81  8 77 16]
 [54 81 28 45]
 [78 76 66 48]]


In [39]:
arr[2]

array([81,  8, 77, 16], dtype=int32)

In [41]:
arr[2,2]

np.int32(77)

In [44]:
print(arr)
arr[0:2,2]

[[79 62 17 74]
 [ 9 63 28 31]
 [81  8 77 16]
 [54 81 28 45]
 [78 76 66 48]]


array([17, 28], dtype=int32)

In [45]:
arr[0:5,2]

array([17, 28, 77, 28, 66], dtype=int32)

In [47]:
arr[ : :2,::2]

array([[79, 17],
       [81, 77],
       [78, 66]], dtype=int32)

## Array filtering

In [ ]:
sales > 400

In [ ]:
sales

In [ ]:
sales[sales>400]

In [ ]:
sales[sales %2 == 0]

In [ ]:
sales

In [ ]:
b = sales[1:4]

In [ ]:
b[0] = 99

In [ ]:
b

In [ ]:
sales

In [ ]:
a = np.array([4,5,6,7])
b = np.array([[9,1,6,6],[21,67,7,7]])

b + 50

In [ ]:
sales

In [ ]:
np.where(sales>400,"high","Low")